### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by codeteo** [john-smilga/react-phone-e-commerce-project#1]
Hi John

Is this code part of a video tutorial or some blog post? If that's the case
would you mind sharing it? 

Thanks and Merry Christmas! :santa: :cake:

**Comment by luisdiogo2071317** [comment]
I'm not him, but you can see in his channel CoddingAddict https://www.youtube.com/channel/UCMZFwxv5l-XtKi693qMJptA (his channel) or from the React playlist https://www.youtube.com/watch?v=-edmQKcOW8s&list=PLnHJACx3NwAdc_hNgACZmnki9tt24N140&index=36 (playlist and has the video that he do this project directly in this link (he has 2 react playlist (one for kind of random tutorials and the other is like sample projects like this one))). Or in freecodecamp.org https://www.youtube.com/watch?v=wPQ1-33teR4 (it has many tutorials like this).
I hope I have helped
